### ISSUE TITLE
How to use it concretely

### ISSUE THREAD

**Issue by shiming-chen** [Samir55/Image2Char#2]
How to use it concretely

**Comment by Samir55** [comment]
## Usage in your code
You should add LineSegmentation.cpp and LineSegmentation.hpp to your project.
```C++
    #include "LineSegmentation.hpp"
    
    // Create an object from LineSegmentation and give to it the image path
    LineSegmentation line_segmentation(img_path);
    
    // Run segment() method to segment lines. The output will be a vector of CV::Mat each representing a line.
    vector<cv::Mat> lines = line_segmentation.segment();
    
```
You should link correctly OpenCV in your working project. if you use CMake see CMakeLists.txt file to see how to add openCV.

* **NOTE** Currently the code has an issue in finding peaks and valleys, which can cause in some cases the lines to be falsely segmented. If you can improve or solve that problem, feel free to make a pull request. you can see the output of these cases in [the this page](https://github.com/Samir55/Image2Lines/wiki/Examples-and-their-results).

**Comment by shiming-chen** [comment]
OK, Thanks!

**Comment by Samir55** [comment]
You are welcome.
