### ISSUE TITLE
The project debug

### ISSUE THREAD

**Issue by shiming-chen** [Samir55/Image2Char#3]
Hello, author. I have debug this project on windows system,but there are some errors. So I want to know whether these codes just work on linux system?

**Comment by Samir55** [comment]
Hello,
@KiM55 Can you give me what errors appeared? 

I have fixed the only error appeared the compiling on visual studio "M_PI is undeclared"

**Comment by shiming-chen** [comment]
The error "M_PI is undeclared" has been fixed,but there still an exception with "Exception thrown at 0x000007FED8C10FE1 (in ucrtbased.dll) (in Image2line.exe): 0xC0000005: An access violation occurred while reading location 0x0000000000000000"

**Comment by Samir55** [comment]
The problem probably that you are not passing the image path to the exe. If you are using an IDE, try adding the image path to the program arguments. Or you can alter main.cpp  to assign to img_path string the actual file path.

**Comment by KiM55** [comment]
Hi!
When I compile the command "./Image2Lines ./t2.png" (I have teken the image in the correct direction) on the linux, there are some error like this.

OpenCV Error: Assertion failed (dims <= 2 && step[0] > 0) in locateROI, file /home/shimingchen/opencv-3.3.0/modules/core/src/matrix.cpp, line 981
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/shimingchen/opencv-3.3.0/modules/core/src/matrix.cpp:981: error: (-215) dims <= 2 && step[0] > 0 in function locateROI

**Comment by KiM55** [comment]
I have solved this problem,Thanks.
But it didn't work well on my datasets.

**Comment by KiM55** [comment]
Hi,author. There is a problem "segmanted fualt(core dumped)" for some image,but itwork well for others images.I think the  reason is that some parameter set errorly.Do you think which parameter should be adjusted and how to adjust it?

**Comment by shiming-chen** [comment]
Hi,author. There is a problem "segmantation fault(core dumped)" for some image,but it work well for others images.I think the reason is that some parameter set incorrectly. Do you think which parameter should be adjusted and how to adjust it?

**Comment by Samir55** [comment]
I will look at it, Sorry I have been busy the previous days :)

**Comment by shiming-chen** [comment]
What's more, the codes will never stop(maybe drop in a recurrence)  for  some images.

**Comment by Samir55** [comment]
If you can send some of these images causing errors, it would be easier for me to know where the problems occur

**Comment by shiming-chen** [comment]
There are some outline-images in the appendix file.
Thank you.




发自网易邮箱大师
在2018年4月4日 21:28，陈使明<13648521576@163.com> 写道：
There are some outline-images in the appendix file.
Thank you.




发自网易邮箱大师
On 4/4/2018 20:06，Ahmed Samir<notifications@github.com> wrote：
If you can send some of these images causing errors, it would be easier for me to know where the problems occur
