### ISSUE TITLE
Words Segmentation

### ISSUE THREAD

**Issue by ghost** [Samir55/Image2Char#5]
@Samir55 Thank you for your hard work,

Your tool is segmenting contours excellently, but can you modify your code to also segment words?

Example:
![initial_lines2](https://user-images.githubusercontent.com/33478216/44923975-909e0a00-ad52-11e8-82cd-16984225b312.jpg)
![contours2](https://user-images.githubusercontent.com/33478216/44923983-97c51800-ad52-11e8-9308-382e23b3ba41.jpg)

Segmented words:
![untitled](https://user-images.githubusercontent.com/33478216/44925643-9e09c300-ad57-11e8-96c2-090bf3826b1f.png)

**Comment by tonsquemike** [comment]
Dear @christophered, The project identify components, so to form words you can try component clustering, it should be another project.
Your proposed feature depends on the language, so, is necessary to custom the clustering parameters according to the language. 

Regards.

**Comment by i-radwan** [comment]
Actually, this project was part of our bigger [project](https://github.com/i-radwan/Image2Code), there we do Word (with naive threshold approach) and Character segmentation (more complex approaches) too, you can check the source code there if this approach fits you (which seems to be the case with your given example) 😄

**Comment by Samir55** [comment]
@christophered, Image2lines as mentioned above is for line segmentation and if you need to do word segmentation it means another project. You can try our complete project or you can read find_contours() function in LineSegmentation Class and also read this issue https://dsp.stackexchange.com/questions/2564/opencv-c-connect-nearby-contours-based-on-distance-between-them, what you should focus on is to use find_contours() then find a method to merge the near contours. But this method should only work in images like the one you have included. Let me know if there is any other issue.

**Comment by ghost** [comment]
Thanks for your help, I will be continuing topic at Image2Code
